#!/usr/bin/env bash
# import_kit.sh — Medieval Village MegaKit -> NOVAForge content pipeline.
#
# Converts the curated piece set from the kit's glTF sources into the engine's
# cooked mesh format (.nfmesh, MeshAsset v1) and writes a text manifest the
# game reads at startup:
#
#   <out>/MedievalKit.manifest
#
# Manifest line:
#   piece <name> mesh=<rel .nfmesh> tex=<BaseColor stem> min=x,y,z max=x,y,z tris=<n>
#
# The dominant material of a piece (the submesh covering the most triangles)
# selects its BaseColor texture. The runtime material model is one material per
# entity (Renderer3D binds obj.material_handle for every submesh of the mesh),
# so a wall whose wood trim is 6 of its 86 triangles reads as plaster — which is
# what it visually is.
#
# Usage:  bash import_kit.sh <kit-glTF-dir> <out-content-dir> [NFModelImporter.exe]
#
# Idempotent: re-running re-imports every piece and rewrites the manifest.

set -uo pipefail

KIT="${1:?usage: import_kit.sh <kit-glTF-dir> <out-content-dir> [importer.exe]}"
OUT="${2:?usage: import_kit.sh <kit-glTF-dir> <out-content-dir> [importer.exe]}"
IMPORTER="${3:-}"

if [ -z "$IMPORTER" ]; then
    for cand in ./build/DebugNinja/bin/NFModelImporter.exe ./build/debug/bin/NFModelImporter.exe; do
        [ -x "$cand" ] && IMPORTER="$cand" && break
    done
fi
if [ ! -x "$IMPORTER" ]; then
    echo "import_kit.sh: NFModelImporter.exe not found; pass it as arg 3" >&2
    exit 1
fi

MESH_DIR="$OUT/Meshes"
TEX_DIR="$OUT/Textures"
mkdir -p "$MESH_DIR" "$TEX_DIR"

# --- curated piece set -------------------------------------------------------
# Grouped by role. Every name must exist as <name>.gltf in the kit.
PIECES=(
    # Walls — plaster (the village's main wall material)
    Wall_Plaster_Straight Wall_Plaster_Straight_L Wall_Plaster_Straight_R
    Wall_Plaster_Straight_Base Wall_Plaster_Door_Flat
    Wall_Plaster_Window_Wide_Flat Wall_Plaster_Window_Thin_Round
    Wall_Plaster_WoodGrid Wall_Arch Wall_BottomCover
    # Walls — uneven brick (the old, weathered look)
    Wall_UnevenBrick_Straight Wall_UnevenBrick_Door_Flat
    Wall_UnevenBrick_Window_Wide_Flat
    # Corners
    Corner_Exterior_Brick Corner_Exterior_Wood Corner_ExteriorWide_Brick
    Corner_Interior_Big Corner_Interior_Small
    # Floors
    Floor_WoodDark Floor_Brick Floor_RedBrick Floor_UnevenBrick Floor_WoodLight
    # Roofs
    Roof_RoundTiles_4x4 Roof_RoundTiles_6x6 Roof_RoundTiles_8x8
    Roof_RoundTiles_4x6 Roof_Wooden_2x1 Roof_2x4_RoundTile
    Roof_Front_Brick4 Roof_Front_Brick6 Roof_Tower_RoundTiles Roof_Dormer_RoundTile
    # Roof overhangs / eaves
    Overhang_Roof_Plaster Overhang_Roof_UnevenBricks Overhang_Plaster_Long
    Overhang_Plaster_Corner Overhang_Side_Plaster_Long_L Overhang_Side_Plaster_Long_R
    # Doors, frames, windows, shutters
    Door_1_Flat Door_2_Flat Door_4_Flat Door_1_Round
    DoorFrame_Flat_WoodDark DoorFrame_Round_WoodDark
    Window_Wide_Flat1 Window_Thin_Flat1 Window_Wide_Round1
    WindowShutters_Wide_Flat_Open WindowShutters_Thin_Flat_Open
    # Balconies, stairs, hole covers
    Balcony_Simple_Straight Balcony_Cross_Straight
    Stairs_Exterior_Straight Stairs_Exterior_Platform Stair_Interior_Simple
    # Props
    Prop_Crate Prop_Wagon Prop_Chimney Prop_Chimney2 Prop_Support
    Prop_Brick1 Prop_Brick2 Prop_Vine1 Prop_Vine4 Prop_Vine6
    Prop_WoodenFence_Single Prop_WoodenFence_Extension1 Prop_WoodenFence_Extension2
    Prop_MetalFence_Simple Prop_MetalFence_Ornament
    Prop_ExteriorBorder_Straight1 Prop_ExteriorBorder_Corner
)

MANIFEST="$OUT/MedievalKit.manifest"
REVIEW="$OUT/MedievalKit.materials.txt"
{
    echo "# NOVAForge Medieval Village MegaKit manifest"
    echo "# generated by Samples/MedievalVillage/Tools/import_kit.sh — do not edit by hand"
    echo "# source: Medieval Village MegaKit[Standard]"
    echo "# fields: piece <name> mesh=<rel> tex=<BaseColor stem> min=x,y,z max=x,y,z tris=<n>"
} > "$MANIFEST"
echo "# piece|material|texture|tris  (material choice review)" > "$REVIEW"

# texture_for <MI_Material> -> BaseColor texture stem in the kit's Textures/ dir.
#
# The kit's naming is T_<Thing>_BaseColor with two exceptions that are named for
# what they depict rather than after the material: the vine's leaf map and the
# window glass gradient. Both are mapped explicitly rather than derived, so a
# rename in the kit fails loudly (TEXTURE-MISSING below) instead of silently
# binding the wrong map.
texture_for() {
    case "$1" in
        MI_WoodTrim|MI_WoodTrim_Wear) echo "T_WoodTrim_BaseColor" ;;
        MI_Plaster)                   echo "T_Plaster_BaseColor" ;;
        MI_UnevenBrick)               echo "T_UnevenBrick_BaseColor" ;;
        MI_Brick)                     echo "T_Brick_BaseColor" ;;
        MI_RedBrick)                  echo "T_RedBrick_BaseColor" ;;
        MI_RoundTiles)                echo "T_RoundTiles_BaseColor" ;;
        MI_RockTrim)                  echo "T_RockTrim_BaseColor" ;;
        MI_Vine)                      echo "T_VineLeaf" ;;
        MI_WindowGlass)               echo "T_WindowGradient" ;;
        # The kit ships no BaseColor map for its ironwork: MI_MetalOrnaments is a
        # flat metal shader in the source project. RockTrim is the closest
        # greyscale stone/iron map the kit does ship, so ironwork reads as dark
        # metal rather than as a missing texture.
        MI_MetalOrnaments)            echo "T_RockTrim_BaseColor" ;;
        *)                            echo "T_${1#MI_}_BaseColor" ;;
    esac
}

# Pieces where the automatic choice is visually wrong. Kept explicit and short:
# every entry here is a piece whose *dominant* material is a detail surface.
#
#   Door_2_Flat / Door_4_Flat — the dominant material is the iron banding
#     (6032 and 1044 triangles of MI_MetalOrnaments) and the plank body is
#     MI_WoodTrim. A door reading as solid iron is wrong; the wood is the door.
#   Prop_MetalFence_* — the same ironwork with no wood in the piece at all, so
#     the RockTrim default above is right for them and they need no entry.
piece_material_override() {
    case "$1" in
        Door_2_Flat) echo "MI_WoodTrim" ;;
        Door_4_Flat) echo "MI_WoodTrim" ;;
        *)           echo "" ;;
    esac
}

# parse_report <report-file> <piece-name>
# prints one tab-separated line: min \t max \t tris \t material
parse_report() {
    awk -v piece="$2" '
        /^meshes: /            { section = "mesh";  next }
        /^materials: /         { section = "mat";   next }
        /^skins: /             { section = "other"; next }
        /^animations: /        { section = "other"; next }
        /^skipped/             { section = "other"; next }
        /^nodes: /             { section = "other"; next }

        section == "mesh" && /bounds min/ && !got_bounds {
            #   bounds min (-1, -0.00209588, -0.314) max (1, 3.12269, 0.0924467)
            line = $0
            sub(/.*bounds min \(/, "", line)
            split(line, parts, /\) max \(/)
            mn = parts[1]
            mx = parts[2]
            sub(/\).*/, "", mx)
            gsub(/ /, "", mn)
            gsub(/ /, "", mx)
            min_s = mn
            max_s = mx
            got_bounds = 1
        }
        section == "mesh" && /verts, [0-9]+ tris/ && !got_tris {
            #   [0] <path>: 134 verts, 86 tris, 2 submesh(es)
            # Match "<n> tris" rather than counting integers: the file path on
            # this line ends in "#Cube.027", and a numeric split counts that 027.
            if (match($0, /[0-9]+ tris/)) {
                t = substr($0, RSTART, RLENGTH); sub(/ tris/, "", t)
                tris_s = t + 0
            }
            got_tris = 1
        }
        section == "mesh" && /^      submesh [0-9]+: material slot/ {
            #   submesh 0: material slot 0, 80 tris, 122 verts
            slot = $0; sub(/.*material slot /, "", slot); sub(/,.*/, "", slot)
            if (match($0, /[0-9]+ tris/)) {
                t = substr($0, RSTART, RLENGTH); sub(/ tris/, "", t)
                if (t + 0 > best_tris) { best_tris = t + 0; best_slot = slot + 0 }
            }
        }
        section == "mat" && /^  \[[0-9]+\] / {
            #   [0] MI_WoodTrim: baseColor (1, 1, 1, 1), metallic 0, roughness 1
            idx = $0; sub(/^  \[/, "", idx); sub(/\].*/, "", idx)
            nm  = $0; sub(/^  \[[0-9]+\] /, "", nm); sub(/:.*/, "", nm)
            mat_name[idx + 0] = nm
            mat_count = idx + 0
        }
        END {
            # Pick the material that names the piece, falling back to the one
            # covering the most triangles.
            #
            # "Dominant triangles" alone is wrong here: the wood trim of
            # Wall_Plaster_Straight is 80 of its 86 triangles, so it would read
            # as a wooden wall. The kit names every piece after the material that
            # defines it (Wall_Plaster_*, Wall_UnevenBrick_*, Floor_Brick,
            # Roof_*RoundTile*), so a material whose own name appears in the
            # piece name wins.
            #
            # MI_WindowGlass is excluded from the name match: Window_Wide_Flat1
            # contains "window", and picking the glass pane would make a whole
            # window frame out of glass. Glass is a detail surface, never a piece.
            norm_piece = tolower(piece)
            gsub(/[^a-z0-9]/, "", norm_piece)
            best_len = 0; chosen = ""
            for (i = 0; i <= mat_count; ++i) {
                cand = mat_name[i]
                if (cand == "") continue
                if (cand == "MI_WindowGlass") continue
                key = tolower(cand)
                sub(/^mi_/, "", key)
                sub(/_wear$/, "", key)
                gsub(/[^a-z0-9]/, "", key)
                if (key == "" || index(norm_piece, key) == 0) continue
                if (length(key) > best_len) { best_len = length(key); chosen = cand }
            }
            if (chosen == "") chosen = mat_name[best_slot]
            printf "%s\t%s\t%d\t%s\n", min_s, max_s, tris_s + 0, chosen
        }
    ' "$1"
}

ok=0; fail=0; missing=0
for piece in "${PIECES[@]}"; do
    src="$KIT/$piece.gltf"
    if [ ! -f "$src" ]; then
        echo "MISSING  $piece.gltf" >&2
        missing=$((missing+1))
        continue
    fi

    # One invocation: --info prints the report AND --output still writes the mesh.
    report="$("$IMPORTER" --input "$src" --output "$MESH_DIR/$piece.nfmesh" --info 2>/dev/null)"
    if [ ! -f "$MESH_DIR/$piece.nfmesh" ]; then
        echo "CONVERT-FAIL $piece" >&2
        fail=$((fail+1))
        continue
    fi

    printf '%s\n' "$report" > /tmp/nf_kit_report.txt
    parsed="$(parse_report /tmp/nf_kit_report.txt "$piece")"
    min_s="$(printf '%s' "$parsed" | cut -f1)"
    max_s="$(printf '%s' "$parsed" | cut -f2)"
    tris_s="$(printf '%s' "$parsed" | cut -f3)"
    mat_name="$(printf '%s' "$parsed" | cut -f4)"

    [ -z "$mat_name" ] && mat_name="MI_Plaster"
    override="$(piece_material_override "$piece")"
    [ -n "$override" ] && mat_name="$override"
    tex_stem="$(texture_for "$mat_name")"
    echo "$piece|$mat_name|$tex_stem|$tris_s" >> "$REVIEW"

    echo "piece $piece mesh=Meshes/$piece.nfmesh tex=$tex_stem min=$min_s max=$max_s tris=$tris_s" >> "$MANIFEST"
    ok=$((ok+1))
done

# --- textures ---------------------------------------------------------------
# Copy only the BaseColor maps the manifest actually names.
tex_src="$(dirname "$KIT")/Textures"
copied=0; tex_missing=0
if [ ! -d "$tex_src" ]; then
    echo "import_kit.sh: texture dir '$tex_src' not found" >&2
fi
while read -r stem; do
    [ -z "$stem" ] && continue
    [ -f "$TEX_DIR/$stem.png" ] && continue
    if [ -f "$tex_src/$stem.png" ]; then
        cp "$tex_src/$stem.png" "$TEX_DIR/$stem.png"
        copied=$((copied+1))
    else
        echo "TEXTURE-MISSING $stem.png" >&2
        tex_missing=$((tex_missing+1))
    fi
# `grep '^piece '` first: the manifest's own header comment documents the
# `tex=` field, and matching it here asked for a texture called "<BaseColor".
done < <(grep '^piece ' "$MANIFEST" | grep -o 'tex=[^ ]*' | sed 's/tex=//' | sort -u)

echo ""
echo "kit import: $ok pieces converted, $fail failed, $missing absent"
echo "textures:   $copied copied, $tex_missing missing"
echo "manifest:   $MANIFEST"
